version: "3.9"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9443:9443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${DATA_ROOT}/portainer:/data"

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - "${DATA_ROOT}/jellyfin/config:/config"
      - "${DATA_ROOT}/media/movies:/media/movies:ro"
      - "${DATA_ROOT}/media/series:/media/series:ro"

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - "${DATA_ROOT}/homepage/config:/app/config"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  default:
    name: tp3-net
